### ISSUE TITLE
Vamos a acabarlo!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m3-evaluacion-intermedia-andreina-proyectos#1]
Buen trabajo @andreina-proyectos  !

Algunas pistas para acabarlo:

- [x] Como sugerencia general, comprueba continuamente tu aplicación en Chrome y el terminal dónde arrancas la app con `npm start`. Si algo falla, hay que arreglarlo antes de continuar.
- [x] Los arrays los pintamos con map, aunque sepamos que hay dos (que nunca lo sabemos)
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Elimina el código comentado
- [x] Revisa los metadatos en index.html (lang, title...)

Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by andreina-proyectos** [comment]
Hello! I think it's all update. Thank you so much! ✌🏼

**Comment by oneeyedman** [comment]
Buen trabajo, Andreína. Solo recuerda que si añadimos funcionalidades tendremos que tb tener en cuenta las nuevas props en las proptypes ;)
